POST http://www.avsoundstation.com/api/login
Content-Type: application/json

{
    "email" : "user@user.com",
	"password" : "password123"
}

###

GET http://www.avsoundstation.com/api/fb-live
Authorization: Bearer 49|jrtBtox7e21Y5KYXsoKhK3cLOHiKwmSAvFe0EV6r
###
GET https://graph.facebook.com/v14.0/447987817190427?fields=embed_html&access_token=EABKJd2InuyUBALUSqyolbK5chdiZBdFDtD54DqdxD59jtzPGNNYmZBeBZAgYBSZAwynTba3vTp5Xi9zZB9UttSO6y98ZAI3dOFUCT3Td4kQYrxIEZCf7bIA5vsNoXk6904dmd9wVlhyA2CVUzCA3L26HkZAxtpsGJ6zayOBX2PTHpjJYM5TjvPAdTQ5MXoMLfogKH1utIfxFUs6tsKUFZBJ7kFZBjWAKsHkoqF9YOpUzWvhwfgvuatjV7t


### 
GET http://www.avsoundstation.com/api/user
Authorization: Bearer 9|vouk8TNqSsvuM10nQVktfw5dj0GabMYr1dH1R8Rc


### 
POST http://www.avsoundstation.com/api/logout
Authorization: Bearer 8|HZVIegiWlCSqAWVGN25KQPMWQy0hD4y97Ikp7Xxa